package niconicotagger.dto.inner.misc

enum class ArtistType {
    Unknown,
    Circle,
    Label,
    Producer,
    Animator,
    Illustrator,
    Lyricist,
    Vocaloid,
    UTAU,
    CeVIO,
    Other,
    OtherVoiceSynthesizer,
    OtherVocalist,
    OtherGroup,
    OtherIndividual,
    Utaite,
    Band,
    Vocalist,
    Character,
    SynthesizerV,
    CoverArtist,
    NEUTRINO,
    VoiSona,
    NewType,
    Voiceroid,
    Instrumentalist,
    Designer,
    VOICEVOX,
    ACEVirtualSinger,
    AIVOICE
}
