app:
  service:
    offline-events: AlbumRelease, Club, Concert, Convention, Other
    default-event-scope: 14d
  api-props:
    database:
      # -> https://vocadb.net/Ar/{artist id}
      vocadb:
        host: "https://vocadb.net"
        publisher-path: "Ar"
      # -> https://beta.vocadb.net/Ar/{artist id}
      vocadb_beta:
        host: "https://beta.vocadb.net"
        publisher-path: "Ar"
    service:
      nnd:
        channel-host: "https://ch.nicovideo.jp"
        thumbnail-host: "https://ext.nicovideo.jp"
        embed-host: "https://embed.nicovideo.jp"
        snapshot-api-host: "https://snapshot.search.nicovideo.jp"
        publisher-props:
          # -> https://www.nicovideo.jp/user/{user id}
          nnd_user:
            host: "https://www.nicovideo.jp"
            publisher-path: "user"
          # -> https://ch.nicovideo.jp/channel/ch{channel id}
          nnd_channel:
            host: "https://ch.nicovideo.jp"
            publisher-path: "channel"
            id-prefix: "ch"
          # -> https://ch.nicovideo.jp/ch{channel id}
          nnd_channel_shortened:
            host: "https://ch.nicovideo.jp"
            id-prefix: "ch"
          # -> https://ch.nicovideo.jp/{channel handle}
          nnd_channel_handle:
            host: "https://ch.nicovideo.jp"

spring:
  web.resources.add-mappings: false
  http.client.connect-timeout: 45s

logging.level.org:.springframework.web: INFO
