name: build and deploy image

on:
  push:
    branches: [ master ]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'niconicotagger' }}


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authorize Docker
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

      - name: Publish
        run: |
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME
